// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weqosgnuiixccghdoccw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcW9zZ251aWl4Y2NnaGRvY2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTg3MDEsImV4cCI6MjA2MDc5NDcwMX0.yXhwmmTjhkgcLG47V-LAP4fELL3zH10vkgH4hlb3zYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);